### ISSUE TITLE
No option to delete a minister's issue available

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#197] opened 2019-10-07 16:01 UTC
# Delete Requirements
- [ ] delete issue option is available
- [ ] prompt notes that all issue content - including associated actions - will be deleted
- [ ] if confirmed the issue and associated actions is deleted

**Comment by LisaMoore1** [comment] 2019-12-18 16:56
@calebissharp RAN099951
- save draft -- no issues saving
- added a minister's issue
- filled required fields
- no missing content identified in red
- save draft = error saving
- exited RUP
- reoponed RUP
- Save Draft = error

2nd time in added a minister's issue and got a "could not submit due to invalid fields" message...but it added the Issue on screen but I can't save
Deleted the existing issue = "could not submit due to invalid fields" = did not save draft --> exited RUP --> reopened RUP = Minister's Issue had been deleted.

**Comment by calebissharp** [comment] 2019-12-18 19:26
@LisaMoore1 This may have just been caused by an error in the deployment. I can't reproduce this locally, so could you give this another try now that test is up-to-date?

**Comment by calebissharp** [comment] 2019-12-18 19:30
@LisaMoore1 Actually hold on, I think I've found something broken. Let me try and fix it.

**Comment by LisaMoore1** [comment] 2019-12-18 20:15
@calebissharp Could be unrelated but also got save error when deleting schedule row. In this case I tried to save multiple times (all with errors) and ended up with multiple copies of that year's schedule. This is one of those inconsistently reproducible problems. Kassia had it happen as well once but also couldn't make it happen again. I can make this one a separate issue if you'd like.

**Comment by calebissharp** [comment] 2019-12-18 21:03
@LisaMoore1 Yes please.

**Comment by LisaMoore1** [comment] 2019-12-18 22:01
@calebissharp No longer getting the error on delete row...or the other issues I was having above. Are you happy with where things are at with this one?

**Comment by calebissharp** [comment] 2019-12-18 22:02
If you can delete minister issues without any problem, I'm good to close this issue.

**Closed** 2019-12-18 22:03 UTC
Labels: ready to test, small
