### ISSUE TITLE
Update client linking page to assign all loc codes for a client number

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#843] opened 2020-06-16 00:46 UTC
Currently in Myra a 'client_id'  is an id assigned to a client number + location.  This however means linking is done very granularly and often requires staff to go relink the same person to another one of their locations.

We can leave the client_id part of it alone but make sure that all the location codes are linked at once for a given client number on that page.  There will be a  separate issue for keeping them in synch in the import job.

**Comment by calebissharp** [comment] 2020-07-08 17:36
Should be resolved by #852

**Comment by LisaMoore1** [comment] 2020-07-23 17:02
@micheal-w-wells I’ve got some questions here re. removing the option to assign a different user (BCeID) to the different location codes.  Also noted that there are differences in the Step 2 drop down depending on whether you enter search text (ex. McFee) versus scroll through list without entering search text.  I can’t pin down exactly what the issue is except I wonder if it might be grouping locations based on last name (? There are two McFees but that doesn’t seem to hold if you scroll versus search Redl so not sure). I’ve attached images that show/explain my questions. 

![F4775D82-4DE4-4716-877E-6938D88A299F.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/d6c18ab6-a3b8-4daf-8bfe-e14c4a2e620f)
![D9E20CA1-13C1-4EB4-BA1D-5BAB88B60BEC.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/7a540a2e-9eef-412a-8459-5b961de543b8)
![CB367668-D932-4883-BAE8-9F6BF36725BA.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/23fb2a2b-820b-452b-aaf1-cf1ae4c009c1)

**Comment by calebissharp** [comment] 2020-07-29 14:32
@micheal-w-wells Can you show me what's in `ref_client` for those two clients? (#00002178, #00033091)

**Closed** 2020-10-21 18:09 UTC
Labels: Task, ready to test
