### ISSUE TITLE
As staff person, selecting recommend ready or recommend not ready is saving but not changing status such that decision maker can action (Attempted RAN099961 (amendment))

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#895] opened 2020-08-06 16:40 UTC

**Comment by LisaMoore1** [comment] 2020-08-06 16:45
![RAN099961 Recommend Ready.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/f395defc-41a4-46b8-abec-37aac053b424)

**Comment by calebissharp** [comment] 2020-08-06 20:59
In your screenshot, is this after you selected "recommend (not) ready"?

**Comment by LisaMoore1** [comment] 2020-08-06 21:05
Yes.

Lisa

**Comment by calebissharp** [comment] 2020-08-07 15:00
Most likely a duplicate of #896

**Closed** 2020-08-25 17:01 UTC
Labels: Bug
