### ISSUE TITLE
schedule rows allows for entry of negative time

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#576] opened 2020-02-10 21:33 UTC
If a range officer gets their dates backwards negative days are allowed, throwing off AUM calc

![image](https://user-images.githubusercontent.com/955467/74192232-f6f6af80-4c09-11ea-8bb7-2b35b54689d4.png)

**Comment by calebissharp** [comment] 2020-02-10 23:00
Duplicate of #533

**Closed by calebissharp** 2020-02-10 23:00 UTC
