### ISSUE TITLE
Range officer gets white screen on clicking plan date

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#588] opened 2020-02-12 22:54 UTC
User has tried:

Clearing cache, trying again

I have tried to reproduce:
Same browser version
Using same data
No dice

Going to try another browser next.

**Comment by micheal-w-wells** [comment] 2020-02-21 17:52
From the RO's chrome console on hitting inspect on the white screen:

@calebissharp this one mean much to ya?

![image](https://user-images.githubusercontent.com/955467/75058416-d3e0c100-548f-11ea-81c7-dc51c90bf04b.png)

**Comment by micheal-w-wells** [comment] 2020-02-21 17:53
RAN075154 @LisaMoore1

**Comment by calebissharp** [comment] 2020-02-27 17:05
@micheal-w-wells Do you have any more info on this?

**Comment by micheal-w-wells** [comment] 2020-02-27 17:31
Nope just the one single user/RAN.

**Comment by calebissharp** [comment] 2020-02-27 19:20
Going to be a bit tricky to narrow down the issue without being able to reproduce it locally. Info on what the contents of the plan are, what status it's in, and what it looks like in the database could be important.

**Comment by micheal-w-wells** [comment] 2020-03-09 15:23
When your ready next to pick up a task swing by my desk we'll get you whatever data you need from this RAN in prod @calebissharp

**Comment by calebissharp** [comment] 2020-03-09 20:22
@micheal-w-wells Can you send me the results of

```sql
select * from plan where agreement_id = ?;
```

for this RAN?

**Comment by LisaMoore1** [comment] 2020-03-19 02:48
Not Able to test this one so moving to closed for now.

**Closed** 2020-03-19 02:58 UTC
Labels: XS, bug, ready to test
