### ISSUE TITLE
Private Land Deduction (in Pasture) should only accept whole numbers between 0 and 100

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#440] opened 2020-01-11 03:45 UTC
Prevent errors in staff entering PLD as a decimal (ex. 0.1 for 10%) and exceeding (I’ve seen 125 — and I’m not sure how a cow can be somewhere more than 100 percent of the time)

If number outside those parameters — error message something like “Percentage must be between 0 and 100”

**Comment by calebissharp** [comment] 2020-01-13 17:10
@LisaMoore1 I can't reproduce. When trying to enter a percent outside of that range I get an error: 
![image](https://user-images.githubusercontent.com/8854811/72276320-834e8c00-35e4-11ea-8c5d-bef4b492ba96.png)

**Comment by LisaMoore1** [comment] 2020-01-13 17:47
@calebissharp OK -- good.  I was battling connection speed and drag so if you get an error I'm happy.

**Comment by calebissharp** [comment] 2020-01-13 18:00
Let me know if you see it again though, in case I overlooked something. Could also older data from before validation was added.

**Comment by calebissharp** [comment] 2020-01-13 19:05
@LisaMoore1 Also, keep in mind since we added offline support, you're really going to want to clear the cache before testing.

**Comment by calebissharp** [comment] 2020-01-16 18:48
Closing until this can be reproduced again.

**Closed by calebissharp** 2020-01-16 18:48 UTC
