### ISSUE TITLE
Non-use issue 

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/range-web#870] opened 2020-07-20 16:51 UTC
From @micheal-w-wells's email:

"Sarah has had this one for awhile, 2 things (may or may not be related):

1) Animals say as not provided when she selected 0
2) It doesn't let her recommend ready and says there is a problem with the schedule, the only anomalous bit other than above is that they are non use years, and I'm wondering if there is some funny javascript math going on, playing in the browser console i wonder if this is a hint:

 ![RAN073906.png](https://images.zenhubusercontent.com/5e78e949a7e29c75200dbef5/fa6722a3-de1e-4923-8582-3105cb73f05f)

She has had this for awhile and bad on me i lost it in the woodwork and lost track of it, but she has a good point that a lot of other non use agreements would have the same issue so we should get the guys to look at it if that makes sense to you also."

**Comment by calebissharp** [comment] 2020-07-20 17:05
Having trouble reproducing this one. I'm setting `# of Animals` to 0 and my non-use is also 0.

**Comment by calebissharp** [comment] 2020-07-21 17:16
@micheal-w-wells Can you check what's in the database for this RAN?

**Comment by calebissharp** [comment] 2020-07-29 14:49
@micheal-w-wells Just going to ping you here again.

**Comment by calebissharp** [comment] 2020-07-31 13:29
Closing as duplicate of #888

**Closed by calebissharp** 2020-07-31 13:29 UTC
