### ISSUE TITLE
Total schedule AUMS including PLD AUMs

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#405] opened 2019-12-17 00:33 UTC
![image.png](https://images.zenhubusercontent.com/5d928234be909100019889b9/87f0107a-135b-41ff-8f7a-4c3ddc1a51ce)

Total AUM should add up to just  406.8

**Comment by micheal-w-wells** [comment] 2019-12-17 01:38
#406 actually causes the same result as what Todd had brought forward, not sure what's going on just yet.

**Comment by micheal-w-wells** [comment] 2019-12-17 01:43
confirmed the offending RAN in prod doesn't have a negative pld percentage

**Comment by calebissharp** [comment] 2019-12-17 17:35
@micheal-w-wells Is the PLD supposed to be subtracted from the crown AUMs?

**Comment by micheal-w-wells** [comment] 2019-12-17 17:52
The crown AUMS should have the already deducted amount for each row, AUTH - PLD = CROWN (this schedule could use another column or IMHO), and total AUMS should add up to the sum of the crown AUMS @calebissharp

**Comment by calebissharp** [comment] 2019-12-17 17:57
@micheal-w-wells So then where do the auth AUMs come from? Is that the same as the "Allowable AUMs" field in the pasture?

**Comment by micheal-w-wells** [comment] 2019-12-17 17:59
@calebissharp yep i think so

**Comment by micheal-w-wells** [comment] 2019-12-17 23:30
@LisaMoore1 we sorted through this one this morning however I don't think we can get it to prod as fast as Todd would like.  I can however point my workstation to prod and produce the PDF if that helps.

**Comment by LisaMoore1** [comment] 2019-12-17 23:48
@micheal-w-wells Could check to see if Todd has immediate needs for an updated PDF. I think he has the status at approved which means there shouldn't be any more changes right now. He may be OK in having to wait until we've got it fixed. Nothing is illegal -- just irritating.

**Comment by calebissharp** [comment] 2019-12-18 21:49
Duplicate of #404

**Closed by calebissharp** 2019-12-18 21:49 UTC
Labels: bug, ready to test
