### ISSUE TITLE
Additional Requirements | no option to delete an existing additional requirement

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#147] opened 2019-10-03 19:12 UTC

**Comment by mccullochk** [comment] 2019-11-23 00:36
I just realized this isn't doable without a backend api change. No endpoint exists to delete an Additional Requirement currently.

**Comment by micheal-w-wells** [comment] 2019-12-10 21:22
@mccullochk how about this one?

**Comment by calebissharp** [comment] 2019-12-16 18:29
@mccullochk Are you going to be working on this?

**Comment by mccullochk** [comment] 2019-12-16 19:47
If I can.

**Comment by calebissharp** [comment] 2019-12-16 20:38
@mccullochk There should be an endpoint now if that's what you mean. I'll work on fixing dev, but for now are you able to get a local instance of the API running?

**Comment by mccullochk** [comment] 2019-12-16 21:39
It looks like `dev` is fixed now.

**Comment by mccullochk** [comment] 2019-12-16 22:11
Actually @calebissharp, maybe it makes sense for you to keep the CRUD tasks on your plate for now and I can keep picking away at the other tasks. Mike says that the PDF thing is also relatively important.

**Comment by calebissharp** [comment] 2019-12-16 22:12
@mccullochk Ok, I'll take this one then.

**Comment by mccullochk** [comment] 2019-12-16 22:12
Thank you!

**Comment by LisaMoore1** [comment] 2020-01-10 18:08
@calebissharp 
Select icon:3-dots —> Delete —> "Cancel" out of popup —> popup closes
For same additional requirement: Select icon:3-dots —> Delete —> no popup is triggered. 

If you "Save draft" —> popup still not triggered 
If you return to work queue and then return to plan and that same additional requirement popup is generated

Popup will still trigger for any OTHER additional requirement (meaning one you haven’t cancelled out of the popup)

**Comment by LisaMoore1** [comment] 2020-01-10 18:29
@calebissharp I also noticed an interesting behaviour that may or may not be related to my sluggish connection speed. 
Sometimes (inconsistently reproducible): Delete Additional Requirement —> popup/Select OK —> popup stays visible like the OK wasn’t triggered —> if you tap “OK” a couple of times the popup eventually closes...and will have deleted an additional requirement for each time you tapped OK on the popup 
The popup eventually closes if you don’t click OK a couple of times...but since there is not indication that OK was selected it is just so tempting to keep clicking and then those extra deletes happen.

**Comment by calebissharp** [comment] 2020-01-10 19:07
@LisaMoore1 I should be able to get fixes for both of those issues. Pretty sure I know the causes.

**Closed** 2020-01-14 23:02 UTC
Labels: ready to test, small
