### ISSUE TITLE
Staff can edit at statuses that are not appropriate 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#326] opened 2019-11-22 14:22 UTC
Either staff **OR** agreement holder (but not both) should have ability to edit on web at any one time. I provided a document before but I think this chart covers it. 

No one can edit: 7, 8, 9, 11, 12, 14, 15, 16, 17, 18
Staff can edit: 6, 13
AH can edit: 1, 4, 5, 10, 19

There may be a couple of statuses above that are very temporary (ex. I think the status changes from 1 (and maybe 5) to 4 as soon as the AH starts working on it). I’m also not sure which status happens when an AH initiates an amendment.

**Comment by micheal-w-wells** [comment] 2019-11-22 17:31
Ok.  Will add this one to list of things we really need tests for.  I still have the doc you sent, will make sure @calebissharp has it if he hasn't seen it.

**Comment by calebissharp** [comment] 2019-11-22 19:06
@LisaMoore1 You have 19 as both not editable by anyone, and also editable by AHs. I assume it shouldn't be editable by agreement holders?

**Comment by LisaMoore1** [comment] 2019-11-22 22:50
@calebissharp  19 should allow AH input -- even if staff think the RUP is ready for them to sign just the way it is we need to allow them the opportunity to change something if they want since we have to review it all again before decision anyway.

**Comment by calebissharp** [comment] 2019-11-22 22:57
@LisaMoore1 Ok, thanks for the clarification!

**Comment by LisaMoore1** [comment] 2019-11-25 21:44
@calebissharp 

**Things to fix:**
- [ ] prevent AH from editing Invasive Plants for status 6,7, 8, 9, 11, 12, 13 14, 15, 16, 17, 18 (can edit at any status now)
- [ ] prevent AH from editing pasture name for all statuses (can edit at any status now) — maybe hide the edit icon and three dots option?
- [ ] prevent staff from making any edits for status 10 (can edit regularly right now)
- [ ]

**Comment by calebissharp** [comment] 2019-11-25 22:25
@LisaMoore1 I can't reproduce your first point, but the other two should be fixed in #341

**Comment by LisaMoore1** [comment] 2019-11-25 23:36
Re. point one.  Cleared Cache on Chrome but not on Safari where I was doing AH side. So...there isn't a save option but the checkboxes are enabled so I can check them off and on which makes me feel like I am editing things even though it doesn't save. So no risk to data integrity but may be confusing to user. Not a priority if more than a XS.

**Comment by calebissharp** [comment] 2019-11-26 00:04
@LisaMoore1 Oh whoops, I was thinking indicator plants, not invasive plants. I'll have another look.

**Comment by calebissharp** [comment] 2019-11-26 00:10
@LisaMoore1 Are the statuses that invasive plants should be editable by an AH the same as the statuses where an AH should be able to edit at all? Or is it a different set?

**Comment by LisaMoore1** [comment] 2019-11-26 00:12
@calebissharp Should be the same as where an AH can edit all.  It is an all or nothing sort of world.

**Comment by calebissharp** [comment] 2019-11-26 00:13
@LisaMoore1 Oh sweet. Just checking because the list you gave above is slightly different.

**Comment by LisaMoore1** [comment] 2019-11-26 00:15
@calebissharp This list above should be a combination of the "nobody can edit" and "Agreement holder can't edit but staff can" lists. That's the intention but the way the day is going what I intended and what was communicated could be two different things.

**Comment by calebissharp** [comment] 2019-11-26 00:16
Alright, no worries :). Fix is deploying now!

**Comment by LisaMoore1** [comment] 2019-11-26 18:36
#132 related

**Comment by LisaMoore1** [comment] 2019-11-27 23:50
@calebissharp Staff should not be able to delete schedules in the statuses they are not permitted to edit. Other than that looks good.

**Closed** 2019-12-03 18:36 UTC
Labels: bug, ready to test, small
