### ISSUE TITLE
Occasional persistent messages at top right 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#556] opened 2020-02-06 00:07 UTC
I have been trying to reproduce this and I can’t seem to figure it out.  Every now and then the save error message or the could not submit due to invalid fields message displays and will NOT go away — even after you log out — which is challenging because it covers the spot you need to see to log out.

**Comment by calebissharp** [comment] 2020-02-06 18:46
Duplicate of #460

**Comment by LisaMoore1** [comment] 2020-02-06 19:26
I'd like to keep this open as it is still happening and a major inconvenience.  It wouldn't be so bad if the "x" in the corner of these messages would let you close them but they don't work so you are stuck with it covering things (like you can't log out). Frustrating.  Maybe if we can't get at why they are persistent we could get at why the X won't close them.  I'm putting it in the backlog and it can be picked up if someone is looking for an issue to work on. 
![persistent message](https://user-images.githubusercontent.com/37600531/73971177-41f38880-48d3-11ea-9c15-0eb190c44b2a.JPG)

**Comment by LisaMoore1** [comment] 2020-02-06 19:28
Got it...duplicate.  WIll add comment re. X to that one.

**Closed** 2020-02-06 19:28 UTC
Labels: bug
