### ISSUE TITLE
staff request: for non-primary agreement holders, don't make submit button be under the 3 dots

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#638] opened 2020-03-16 18:57 UTC
Primary AH gets a big button, others have to look for the 3 dots and click it.  For the less than tech savy it isn't super obvious and a few Range Officers have asked that we make it more obvious.

**Comment by micheal-w-wells** [comment] 2020-03-18 20:57
Struggling to see how to reproduce this one, I have a RUP in test with 2 AH, primary and other both have a submit button not under the 3 dots.

**Comment by micheal-w-wells** [comment] 2020-03-18 21:12
Eventually saw it.  Once the primary has submitted the 'Sign' button is only available to AH # 2 under the 3 dots.

**Comment by micheal-w-wells** [comment] 2020-03-18 22:10
related to #544

**Comment by micheal-w-wells** [comment] 2020-03-26 16:12
@calebissharp if you need one to do today can you help out with this?  I've had a poke but am not 100% on how to go about it just yet, and I've got a couple RO's with myra problems to chase down today.

**Comment by calebissharp** [comment] 2020-03-26 16:35
@micheal-w-wells I'm not totally certain the best way to go about doing this, but I think it is a non-trivial amount of work. Let me know if you still want to go ahead with it today.

**Comment by micheal-w-wells** [comment] 2020-03-26 17:06
@calebissharp when i get off the call let's eyeball it together

**Comment by micheal-w-wells** [comment] 2020-03-26 18:49
/remind @calebissharp to make a PR for what we were doing every 5 seconds until noon

**Comment by LisaMoore1** [comment] 2020-03-27 18:19
@calebissharp Has this been merged? I’m still needing to use the three dots to access the sign submission option rather than a button that says “submit”

**Comment by calebissharp** [comment] 2020-03-27 18:34
It should be. @micheal-w-wells Is there something up with openshift again?

**Comment by micheal-w-wells** [comment] 2020-03-27 19:14
@calebissharp there was one failed one for today (out of memory), so those other builds had no bearing on that issue.  I upped it another 500mb, and changed the run policy to be `serial latest` which means it runs one at a time, but only the most recent so it will discard no longer relevant ones.

The build with your changes made it through yesterday though.  Might want to test that one out thoroughly and make sure your bases are covered.

**Comment by micheal-w-wells** [comment] 2020-03-27 22:38
@ZoeSimon and I tested this and we didn't see the button there.  I'll double check but as far as I can tell deployments are working @calebissharp.

**Comment by ZoeSimon** [comment] 2020-03-27 23:26
@micheal-w-wells says "I added some temp placeholder text to prove deployments and merges are working. Note that even after clearing cache I didn't see the new changes! I had to make sure all my myrange tabs were closed and then clear cache in order for it to work"

![Clipboard - March 27, 2020 4_20 PM](https://user-images.githubusercontent.com/62561887/77808129-75d36a80-7047-11ea-9339-164e926190ab.png)

@calebissharp @LisaMoore1

**Comment by calebissharp** [comment] 2020-03-30 16:13
@LisaMoore1 I can't test this in `test`, since I don't have any multi-AH RANs. Are you still seeing the option in the menu, or are you not seeing a "Sign submission" button at all? If the former, I think it's a cache problem, if the latter, I'll have to look into reproducing.

**Comment by LisaMoore1** [comment] 2020-03-30 16:15
@calebissharp The sign option for the additional holders was under the three dot menu.  In the morning on Friday I closed all windows in all browsers and cleared all history/data in both—which in theory should have given me a correct cache clear.  I’ve done the same again this morning and will try to test again when I’ve got a minute.

**Comment by ZoeSimon** [comment] 2020-03-30 16:23
@calebissharp @LisaMoore1 I just tested this one by signing on the ben.wyatt account as him and leslie.knope have a shared plan under RAN099915, and a "Sign Submission" button was showing up and wasn't hidden under the 3 dots, so I'm thinking this one is all clear? @LisaMoore1 I'd feel more comfortable if you tested and closed it just in case though as I still have rookie status.
![image](https://user-images.githubusercontent.com/62561887/77936566-ea84ef80-7267-11ea-9d11-6fff156fc515.png)

**Comment by LisaMoore1** [comment] 2020-03-30 16:35
Same as for me this morning.  @zoesimon you can go ahead and close this one. 😊

**Closed** 2020-03-30 16:37 UTC
Labels: enhancement, ready to test, small
